export const seedingData = [
    {
        "id": "24080",
        "title": "Temple Run 2: Jungle Fall",
        "description": "Temple Run 2: Jungle Fall is an endless runner game developed by Imangi. Escape from the dangerous demonic apes and avoid all the obstacles and traps that are found along the way. Traverse the beautiful orange forest, avoid traps, dodge dynamic enemies like venus flytraps, and help this fearless treasure hunter escape with the gold idol. But hurry up! The evil monkey monsters are still chasing you! The Jungle Fall map adds some vibrance to the classic Temple Run 2 experience. Are you ready for a familiar yet new exciting adventure? Enjoy the fall season with a brand new map to fall in love with!",
        "instructions": "Move - AD or Left Right arrow keys Jump - W or Up arrow key Slide down- S or Down arrow key",
        "url": "https://html5.gamemonetize.com/pkrsuit51ypgzm64h6ohkjnqvwv1zabz/",
        "category": "Adventure",
        "tags": "Jumping, Race, Racing, run, running",
        "thumb": "https://img.gamemonetize.com/pkrsuit51ypgzm64h6ohkjnqvwv1zabz/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "23235",
        "title": "CrazySteve.io",
        "description": "The game Crazy Steve io was created for fun and fast fighting. The main task in Crazy Steve is to score as many points as possible and be the coolest. To do this, you need to collect diamonds and apples that appear on the map. For diamonds, you charge more experience than apples, but thanks to apples you can recovery your health. A lot of diamonds fall out of the killed rival. Do you understand what we are inclined to? Yes! You need to scatter around the dynamic checkers, shoot from the bow, attack with the sword, shoot from the fireball and use other weapon in every way to kill the rivals, and then take their diamonds to yourself. By the way, be careful, you can undermine yourself, will be more blood! On the map running animals that you can kill and recovery health. With each new level you increase slightly. Together with the volume increases the ability of your character to collect apples and diamonds. But at the same time you gradually slow down and become more vulnerable to attacks by fast, small and agile rivals. Therefore, the Top player quickly opens the hunting season. Players scour the field in search of a 'fat boy'. So the more diamonds you recruit, the sharper the battle becomes! Another feature of Crazy Steve is that you can undermine your own sword. You can throw 4 dynamite at a time. Only after the explosion of one of them you can throw a new one. On the map are scattered different helmets: wooden, iron, gold, diamond and cart, wear them or sit in the cart to be more protected! Apples and diamonds appear on the map constantly. Players usually fight in the center and therefore one should periodically look at the edges of the map to collect diamonds.",
        "instructions": "Mouse move - Move Left mouse button - Attack Right mouse button - Speed up Enter - Chat",
        "url": "https://html5.gamemonetize.com/uqzbzhkjckdjj96mn9sm0mcyoz68tagn/",
        "category": "Multiplayer",
        "tags": "Action, Animal, Block, Bow, Fun, Funny, Minecraft, Shooter, Sword",
        "thumb": "https://img.gamemonetize.com/uqzbzhkjckdjj96mn9sm0mcyoz68tagn/512x384.jpg",
        "width": "1000",
        "height": "800"
    },
    {
        "id": "23234",
        "title": "EvoWarriors.fun",
        "description": "EvoWarriors.fun is a free fantasy style game. Eat steaks, eggs, milk and everything you find to grow in size while you are small, most importantly do not eat amanita, because it reduces your experience and you become smaller! Attack smaller enemies, so you have a better chance of staying alive. You can insurance yourself just run away from large enemies so that they do not kill you with one fell swoop of their powerful weapon or you can donate your experience to the enemy. But you won’t be able to run for a long time, because when you run, your experience decreases. The game has only 15 levels: Knight lvl 1 Knight lvl 2 Knight lvl 3 Assassin lvl 1 Assassin lvl 2 Dwarf lvl 1 Dwarf lvl 2 Dwarf lvl 3 Skeleton lvl 1 Skeleton lvl 2 Skeleton lvl 3 Golem lvl 1 Golem lvl 2 Orc lvl 1 Orc lvl 2 Orc lvl 3 Can you get to level 16 and become the biggest and strongest in the game? Hint: for players who disable the ad blocker, an additional 20% of experience is awarded! One of the effective attack tactics: approach the enemy on the left side so that it is to your right and from your sword, then - immediately attack first!",
        "instructions": "Attack - left mouse button Speed Up - right mouse button",
        "url": "https://html5.gamemonetize.com/gf8ve9ub8patlfqyyeplw3e40kjriymz/",
        "category": "Multiplayer",
        "tags": "Battle, Fantasy, Knight, War",
        "thumb": "https://img.gamemonetize.com/gf8ve9ub8patlfqyyeplw3e40kjriymz/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "23233",
        "title": "MineEnergy.fun",
        "description": "MineEnergy.fun - is a free Minecraft style game. Mine resources, buy in the store and put generators for energy production, put selling blocks to sell resources and energy for money. Buy improved tools, armor, new generators, and automatic miners. Protect your buildings with walls and Tesla coils. Get resources from ores: coal ore iron ore golden ore diamond ore uranium ore Each type of ore has its own miner for automatic extraction of resources. Put the generators: manual generator - generates energy from interacting with it. Not effective, but suitable when there are no other options. solar generator - generates energy from sunlight. wind generator - generates energy from wind. coal generator - generates energy from coal. geothermal generator - generates energy from lava. water turbine - generates energy from water. nuclear generator - generates energy from uranium. Each generator consumes something (or not) and produces energy. Place the “Small seller” or “Big seller” block to sell resources for money. For money you can buy an improved tools: wooden pickaxe - the easiest pickaxe. It produces a few resources, but the cheapest. iron pickaxe - improved pickaxe. Mining more resources. With it, you can mine gold. golden pickaxe - improved pickaxe. Mining more resources. With it, you can mine diamonds. diamond pickaxe - the best pick that does not require energy. Mining more resources. With it, you can mine uranium. drill - dimple electric drill. It extracts more resources, but consumes energy during operation. diamond drill - the best tool for resource extraction. It extracts a huge amount of resources per hit, but also consumes more energy. wrench - removes your blocks. Hit your block with a wrench to remove the block. You can buy armor: leather armor - hard to call it armor, but it's better than nothing. iron armor - absorbs part of the damage. golden armor - better than iron armor, it absorbs more damage. And players like to show off at her. diamond armor - the most durable armor that does not require energy. A great choice if you do not have generators, but have a lot of money o_O nano armor - carbon fiber armor. It protects better than a diamond armor but consumes energy while absorbing damage. quantum armor - the best armor! Effectively absorbs most of the damage, but consumes more energy. Alas, it does not protect against coronavirus. Protect your buildings with walls, Tesla coils and put a bed that will revive you after death. MineEnergy will let you have fun and not let you get bored!",
        "instructions": "W A S D - Move Left Mouse Button - Attack Place block Left Shift - Speed up E - Shop",
        "url": "https://html5.gamemonetize.com/bs2466de0q7tdyhevlqw5djxerbabbzm/",
        "category": "Multiplayer",
        "tags": ".io, .io Games, Block, Fight, Fighting, Mine, Minecraft, Miner, Multiplayer, Pixel, Strategy",
        "thumb": "https://img.gamemonetize.com/bs2466de0q7tdyhevlqw5djxerbabbzm/512x384.jpg",
        "width": "1000",
        "height": "800"
    },
    {
        "id": "22886",
        "title": "Shoot Bubbles",
        "description": "Shoot Bubbles, classical bubble shooter game and poping all bubbles in each level.",
        "instructions": "Find the bubbles of the same color aim and shoot you can eliminate all bubbles on the field ",
        "url": "https://html5.gamemonetize.com/l7tc8czsopt46oopaufh222mq7o60527/",
        "category": "Shooting",
        "tags": "Bubble, Bubble Shooter, Shoot",
        "thumb": "https://img.gamemonetize.com/l7tc8czsopt46oopaufh222mq7o60527/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "22883",
        "title": "Fashion Tattoo Studio 4",
        "description": "Today Zoe's tattoo shop has a limited-time discount offer. Zoe will design back tattoos for all customers for free. Three fashion girls want to try and each of them has their own interested design. Sofia likes butterfly. Bella likes rose. Rebecca likes birds. Help Zoe to draw these pictures and make tattoos. Have fun with Fashion Tattoo Studio.",
        "instructions": "Mouse click or tap to play",
        "url": "https://html5.gamemonetize.com/tnw9gudn4cn34mmm73zc7mzego5h4lfj/",
        "category": "Girls",
        "tags": "Coloring, Decorate, Design, Fashion, Girl, Girls, Kids, Simulation",
        "thumb": "https://img.gamemonetize.com/tnw9gudn4cn34mmm73zc7mzego5h4lfj/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "22881",
        "title": "Stupid Zombies Game",
        "description": "Stupid Zombies is a puzzle zombie shooting game developed by MarketJS. In this game, you’ll fight against zombies by aiming correctly with your gun and shooting bullets with rebounds. Work on your angles to score the highest number of zombie kills in the least amount of bullets. Go ahead and demonstrate the power of your aim !",
        "instructions": "Tap the screen to shoot",
        "url": "https://html5.gamemonetize.com/w40uqcj11jyv8bbtwwhm77jttlo31h13/",
        "category": "Boys",
        "tags": "Physics, Puzzle, Shooting, Skills, Zombie",
        "thumb": "https://img.gamemonetize.com/w40uqcj11jyv8bbtwwhm77jttlo31h13/512x384.jpg",
        "width": "1280",
        "height": "720"
    },
    {
        "id": "22107",
        "title": "My Huggy Wuggy Nightmare",
        "description": "We moved in a new neighbourhood just few days ago. It's a peaceful and neighbours are nice. But there is a story about this man monster Huggy Wuggy. It's a disturbing story... After weeks of unexplained murders, the ominous unknown killer is still on the rise. After little evidence has been found, a young boy states that he survived one of the killers attacks and bravely tells his story.",
        "instructions": "W A S D to walk around Mouse to Look around Left Mouse Button to Fire Right Mouse Button to Aim Mouse Wheel To Change Weapons G for Grenades R to Reload F to Pickup Items Left Shift to Run Left CTRL to Crouch X to Prone V ",
        "url": "https://html5.gamemonetize.com/hw2d4tdcdq4az7sf4zy8abjki1s3hocg/",
        "category": "Shooting",
        "tags": "Collecting, Escape, Shooter, weapons, Zombie",
        "thumb": "https://img.gamemonetize.com/hw2d4tdcdq4az7sf4zy8abjki1s3hocg/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "22023",
        "title": "Kill The King",
        "description": "The most important and most omnipotent has always been the king, everything was allowed to him, according to his decision they could execute and get rich, he lived for his own pleasure, but not many people know that being a monarch was also dangerous. How many people claimed the throne, and not all of them were strangers to the royal family, there were even such sisters and brothers who wanted to get the throne at any cost and killing the king was only in their favor. Unfortunately, you can’t get away from this, and if you are ready to take on the heavy burden of a royal person or one of the Royal Assassins, nothing is stopping you, press start and go!",
        "instructions": "Click Space button",
        "url": "https://html5.gamemonetize.com/th53fdzqzvzoq9bn1caf6uynwf82gx5u/",
        "category": "Clicker",
        "tags": "Adventure, Castle, Click, Clicker, Fight, Fighting, HTML, HTML5, Kill, Killing, King",
        "thumb": "https://img.gamemonetize.com/th53fdzqzvzoq9bn1caf6uynwf82gx5u/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "22022",
        "title": "Jump Into Wow",
        "description": "Help the character get to the highest point in order to catch the villain who has stolen an important thing. Beware of falls from a height, as the test will end ahead of time and fail to complete the main goal.",
        "instructions": "Clcik on the screen or use mose ",
        "url": "https://html5.gamemonetize.com/kuvxeoiruc1t7r4r7mddbpnwcwl7yi1t/",
        "category": "Adventure",
        "tags": "Action, Adventure, Cartoon, Cartoon Network, Disney, Highscore, HTML, HTML5, Hypercasual, jump, Jumping",
        "thumb": "https://img.gamemonetize.com/kuvxeoiruc1t7r4r7mddbpnwcwl7yi1t/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "22012",
        "title": "Evil Granny Must Die Ch1",
        "description": "Evil Granny has knocked you down! You know where she lives, and now you can't leave the house. She throw you in her Bunker. You must find 8 books if you want to leave this place alive! Good Luck!",
        "instructions": "W A S D to walk around Mouse to Look around Left Mouse Button to Fire Right Mouse Button to Aim Mouse Wheel To Change Weapons G for Grenades R to Reload F to Pickup Items Left Shift to Run Left CTRL to Crouch X to P",
        "url": "https://html5.gamemonetize.com/yponinqihtbd9g8dglr27yj264o6nidq/",
        "category": "Shooting",
        "tags": "Action, Collecting, Escape, weapons, Zombie",
        "thumb": "https://img.gamemonetize.com/yponinqihtbd9g8dglr27yj264o6nidq/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "21904",
        "title": "Lets Kill Evil Nun",
        "description": "You came to investigate strange happenings at the abandoned Asylum. There are rumors that Evil Nun is behind them. Find 8 crosses, prove her existence and try getting out alive!",
        "instructions": "W A S D to walk around Mouse to Look around Left Mouse Button to Fire Right Mouse Button to Aim Mouse Wheel To Change Weapons G for Grenades R to Reload F to Pickup Items Left Shift to Run Left CTRL to Crouch X to Prone V ",
        "url": "https://html5.gamemonetize.com/my16xxhd5lj5vq5q3jrd7orr3ssv636j/",
        "category": "Shooting",
        "tags": "Collecting, Escape, weapons, WebGL, Zombie",
        "thumb": "https://img.gamemonetize.com/my16xxhd5lj5vq5q3jrd7orr3ssv636j/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "21553",
        "title": "Biohazard Z War",
        "description": "Zombies has taken over the World. There is now way stopping them, only thing left is to SURVIVE. Kill as many as you can, find supplies of ammo, fuel, food and water. Good luck! Features: * 20 levels to play * Earn Coins to buy new weapons * Easy controls * Zombies Body Dismemberment System",
        "instructions": "W A S D to walk around Mouse to Look around Left Mouse Button to Fire Right Mouse Button to Aim Mouse Wheel To Change Weapons G for Grenades R to Reload F to Pickup Items Left Shift to Run Lef",
        "url": "https://html5.gamemonetize.com/vq1xpnav3g0dz1wiku00o3twdam4uh3z/",
        "category": "Shooting",
        "tags": "Action, Fire, weapons, WebGL, Zombie",
        "thumb": "https://img.gamemonetize.com/vq1xpnav3g0dz1wiku00o3twdam4uh3z/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "21552",
        "title": "Evil Granny: City Terror",
        "description": "You are trapped in City. Find and collect 8 Keys and get out. It wont be easy as is sounds. City is hunted by Evil Granny and her puppets. Good luck!",
        "instructions": "W A S D to walk around Mouse to Look around Left Mouse Button to Fire Right Mouse Button to Aim Mouse Wheel To Change Weapons G for Grenades R to Reload F to Pickup Items Left Shift to Run Left CTRL to",
        "url": "https://html5.gamemonetize.com/k1l1ptpuibas9nt1zm31tb8gg398lqdo/",
        "category": "Shooting",
        "tags": "Adventure, Escape, weapons, WebGL, Zombie",
        "thumb": "https://img.gamemonetize.com/k1l1ptpuibas9nt1zm31tb8gg398lqdo/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "21294",
        "title": "Squid Game Swarm",
        "description": "Squid Game Swarm is a 3D shooting game which features non stop shooting experience in squid game environment, you play as the guard and your mission is to protect the doll from hordes of incoming players and try to survive before the time runs out.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/r6hqc7e7u9x13ufgdr2fd101k9ovl6n2/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, Shoot, Shoot 'Em Up, Shooter, Shooting, Unity3D, WebGL",
        "thumb": "https://img.gamemonetize.com/r6hqc7e7u9x13ufgdr2fd101k9ovl6n2/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "21003",
        "title": "Counter Craft 2 Zombies",
        "description": "Counter Craft 2 Zombies features action packed zombie shooting in minecraft world, your mission is to use three different weapons to shoot hordes of incoming zombies and try to survive each round with increasing difficulty.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/lccvcjui45roecfojxto6j8t5ceags7u/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, CSGO, Gun, Minecraft, Shoot, Shoot 'Em Up, Shooter, Shooting, Undead, Unity3D, WebGL, Zombie",
        "thumb": "https://img.gamemonetize.com/lccvcjui45roecfojxto6j8t5ceags7u/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "20941",
        "title": "Call of Ops 3 Zombies",
        "description": "Call of Ops 3 Zombies is a shooting game what features intense zombie shooting experience with realistic physics and three highly detailed maps where your mission is to shoot the given amount of zombies in order to survive each round and get awarded with new weapons.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/cj2i0xkpesbl0e3m3tqf5pqpc6fzvxoh/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, Gun, Shoot, Shoot 'Em Up, Shooter, Shooting, Undead, Unity3D, WebGL, Zombie",
        "thumb": "https://img.gamemonetize.com/cj2i0xkpesbl0e3m3tqf5pqpc6fzvxoh/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "20894",
        "title": "Poppy Strike 2",
        "description": "Poppy Strike 2 features big arsenal of weapons and minecraft themed map where your mission is to shoot all incoming huggy wuggy dolls and try to survive each round in order to win and unlock new guns.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/cx3vqjbc622re67nrmgo2vfp26ixamjq/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, CSGO, Gun, Shoot, Shoot 'Em Up, Shooter, Shooting, Unity3D, WebGL",
        "thumb": "https://img.gamemonetize.com/cx3vqjbc622re67nrmgo2vfp26ixamjq/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "20777",
        "title": "Zombie Vacation 2",
        "description": "Zombie Vacation 2 is a zombie survival shooter with cool graphics, you are special forces soldier lost in tropical island crowded with blood thirsty zombies and your mission is to shoot all incoming zombies and unlock lots of guns in order to survive.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/i6p9zo018e141anwiop9ocqee064272h/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, Gun, Shoot, Shoot 'Em Up, Shooter, Shooting, Undead, Unity3D, War, WebGL, Zombie",
        "thumb": "https://img.gamemonetize.com/i6p9zo018e141anwiop9ocqee064272h/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "20694",
        "title": "The Simple Piano",
        "description": "Simple piano application to learn play the piano and with realistic sounds of instruments. How to Play Piano: Just run your fingers over the real piano tiles, playing live music and feel like a real musician. Features: • It works with all screen resolutions • Full piano keyboard • Multi-Touch • Easy for children",
        "instructions": "Just one Click Tap to play ",
        "url": "https://html5.gamemonetize.com/3ys6b87ick5q71415hbzjaemf36f2csw/",
        "category": "Clicker",
        "tags": ".io, Educational, endless, Family, HTML5, Kid, Kids, Mobile, Music",
        "thumb": "https://img.gamemonetize.com/3ys6b87ick5q71415hbzjaemf36f2csw/512x384.jpg",
        "width": "1024",
        "height": "600"
    },
    {
        "id": "20666",
        "title": "My Tiny Cute Piano",
        "description": "My Tiny Cute Piano is Interactive, colorful, and fun, it's designed to help your little one to learning about keys. This kids educational game will train your child to recognize different piano keys and notes while enjoying the games. It's a Mother's Helper to Keep Children Quiet! ;) Get it Now! Product feature bullets: • Keep Children Quiet! • Cool Graphic • Nice music themes • Funny characters • Endless gameplay • Ideal for all kids",
        "instructions": "Just one Click Touch to play the game ",
        "url": "https://html5.gamemonetize.com/15jldj2vg9hr7iq3xcvjhadpkx3rptjv/",
        "category": "Girls",
        "tags": "Clicker, Family, Girls, HTML, HTML5, Kid, Mobile, Music",
        "thumb": "https://img.gamemonetize.com/15jldj2vg9hr7iq3xcvjhadpkx3rptjv/512x384.jpg",
        "width": "1280",
        "height": "800"
    },
    {
        "id": "20659",
        "title": "Full-Life Deathmatch",
        "description": "Full-Life Deathmatch is a 3D multiplayer game which features intense deathmatch battles with five highly detailed maps and three types of weapons to shoot rival players, try to get the highest amount of frags in order to win.",
        "instructions": "WASD - Move Space - Jump C - Crouch LMB - Shoot RMB - Aim R - Reload P - Pause menu 1 2 3 - Select weapon ",
        "url": "https://html5.gamemonetize.com/j70o3o5gubaaq3awsfhglmrwne6rhrca/",
        "category": "Shooting",
        "tags": "3D, 3D Games, Action, CSGO, Gun, Multiplayer, Shoot, Shoot 'Em Up, Shooter, Shooting, Unity3D, War, WebGL",
        "thumb": "https://img.gamemonetize.com/j70o3o5gubaaq3awsfhglmrwne6rhrca/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "20626",
        "title": "Magical Unicorn Grooming World - Pony Care",
        "description": "Come and find your own unicorn. You will clean out the stable for the poor unicorn, bathe her, and change her horseshoe. After that, you can dress her up and turn her into your magical unicorn! All right, stop hesitating and start the game!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/po7kr0niy1lc2ttc4hcbpl6yw0x730l2/",
        "category": "Girls",
        "tags": "Animal, Cleaning, Dress Up, Fun, Girl, Girls, H5, HTML5, Kid, Kids, Pony",
        "thumb": "https://img.gamemonetize.com/po7kr0niy1lc2ttc4hcbpl6yw0x730l2/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "20624",
        "title": "Blow Kings Game",
        "description": "In Blow Kings, an exciting and unique competition is about to begin, and our guests are all brave and eager to win. Believe me, when the game starts, no matter what already will not make you any mood swings, your eyes are only on the victory. How to adjust your breathing is the key to victory, blow the glass tube with a breath bigger than your opponent, you can win, ready? How many opponents can you beat? Will this session of the blowing king be you?",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/vnaemb0qtvb02asv3q4g5qvviepcd1m6/",
        "category": "3D",
        "tags": "Boys, Hypercasual, Puzzle, War",
        "thumb": "https://img.gamemonetize.com/vnaemb0qtvb02asv3q4g5qvviepcd1m6/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20616",
        "title": "Noob vs Pro Squid Challenge",
        "description": "Squid challenge is waiting for you with a lot of stage friends. The best way to spend time is to be a friend noob and a friend a pro and play two player games. In the first game, you have to move forward without turning his back. In the next game you have to be careful in pulling the rope be the fastest puller and you win. In the next game, reach the finish line with your friend and be the winner of all games and your friend.",
        "instructions": "Noob Player A Press Key Mobile Touch Control Pro Player P Press Key Mobile Touch Control",
        "url": "https://html5.gamemonetize.com/1bfyeyip9alz66ejp66n57waxv4izy88/",
        "category": "Arcade",
        "tags": "2 Player, 2 Player Games, 2D, Action, Adventure, Android, Arcade",
        "thumb": "https://img.gamemonetize.com/1bfyeyip9alz66ejp66n57waxv4izy88/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20606",
        "title": "Survival Brawl 3D Game",
        "description": "Survival Brawl 3d is an online adversarial survival casual game. You will compete with several participants and whoever survives to the end will win. You can choose to fight with your bare hands or pick up your weapons from the ground. Swimming rings, chairs, watermelons, etc. can be your weapons of choice. Defeat your opponents and laugh till the end! Good luck!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/n9a65p34nghov9ax4kmacws03sz7ek8f/",
        "category": "3D",
        "tags": "Avoid, Boy, Fighting, Kid, Skill, Superhero, War",
        "thumb": "https://img.gamemonetize.com/n9a65p34nghov9ax4kmacws03sz7ek8f/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20571",
        "title": "Hair Challenge Online 3D",
        "description": "Become a super fashion model by a hair salon in this hair challenge game 3d. Variety of catwalk beauty race challenging levels with fun race 3d and hair colors at the hair shop with hair dye makeover run to choose your character in the best hair rush walking game. Play this hair challenge run game with the best hair runner game idea now and forget all about other hair games for girls. So don't waste your time and get into this hair challenge 3d hair game and enjoy the most epic race.",
        "instructions": "Tap or click on the screen ",
        "url": "https://html5.gamemonetize.com/u11v7952y95lkh4xdzvvfkrvi2pkuvhl/",
        "category": "Girls",
        "tags": "Arcade, Girl, Girls, Hair, Hypercasual, Online",
        "thumb": "https://img.gamemonetize.com/u11v7952y95lkh4xdzvvfkrvi2pkuvhl/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20570",
        "title": "Buttocks Time 3D",
        "description": "Buttocks Time is a new type of game that tests the ability of reflection. In this seemingly simple but innovative gym. You are now a fitness coach and work together with your team member to complete these challenging tasks. Can you finish it?",
        "instructions": "Tap to play ",
        "url": "https://html5.gamemonetize.com/6zzuyh8fb5326dyuz5lbbiedp4o0xuaq/",
        "category": "Hypercasual",
        "tags": "3D, 3D Games, Arcade, Girl, Girls, Hypercasual, Obstacle, Online, Physics, Skill",
        "thumb": "https://img.gamemonetize.com/6zzuyh8fb5326dyuz5lbbiedp4o0xuaq/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20569",
        "title": "Perfect Salon",
        "description": "Some girls really need a stylist. In today's game for girls, you will be in the role of a stylist who will help cute girls become even better than they are with makeup. Only you will help them and win their hearts! In this game, you can make a variety of makeup for different people, get rewards for it and see the sincere emotions of people grateful to you for your work. The first visitors are already waiting their turn for you to make them a cool facial. Here comes the first client. She has a very overgrown eyebrow. So get a special tool and get them back to normal, get them shaped nicely.",
        "instructions": "Tap to play ",
        "url": "https://html5.gamemonetize.com/l0p28elntiwzztsyi16raes7yycn6we3/",
        "category": "Hypercasual",
        "tags": "3D, 3D Games, Arcade, Girl, Girls, Hypercasual",
        "thumb": "https://img.gamemonetize.com/l0p28elntiwzztsyi16raes7yycn6we3/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20527",
        "title": "Panda Magic Drawing Rescue",
        "description": "The little fairy hopes to have an assistant who can work with her to help forest residents with the magic brush. Come and sign up now! Learn to draw by tracing the lines in the sketch: Birthday cake, Christmas gift box, round sun, bubble skirt of the little princess. Kinds of creative sketches for you to enjoy and create paintings of your own!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/aotagefzki0v1z8btrbsonxghcrn2pbp/",
        "category": "Girls",
        "tags": "Animal, Color, Coloring, Draw, Drawing, Fun, Girl, Girls, H5, HTML5, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/aotagefzki0v1z8btrbsonxghcrn2pbp/512x384.jpg",
        "width": "890",
        "height": "1480"
    },
    {
        "id": "20526",
        "title": "Magica.io Game",
        "description": "Welcome to the game world of Magica.io. Are you ready to defeat all your opponents and become the strongest player? Come on and join this thrilling battle. In this game, you will use magic elements and kill each other with your enemies in a brutal arena. Everyone is fighting for themselves. Collect magic elements to make yourself more powerful. Defeat everyone with weapons and climb to the top of the leaderboard. Have fun!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/s8u9yscdyd57hshdwa5z6h3gs60euwq5/",
        "category": "3D",
        "tags": "Arcade, Arena, Avoid, Boys, Collection, Highscore, Kids, Killing, Magic, Skill",
        "thumb": "https://img.gamemonetize.com/s8u9yscdyd57hshdwa5z6h3gs60euwq5/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20510",
        "title": "Tailor Kids - Fashion Designer",
        "description": "Tailor is a useful, respectable profession. Because everyone wants a unique nice cloth. Now you are a little tailor. Your friends want a beautiful skirt which is custom-made. It is time to show your skill. Let us do it! I believe you could make a perfect skirt.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/1s55u1vcjxcuna67ezodn1l0oms3a6mt/",
        "category": "Hypercasual",
        "tags": "Crafting, Dress Up, Fashion, Fun, Girl, Girls, H5, HTML5, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/1s55u1vcjxcuna67ezodn1l0oms3a6mt/512x384.jpg",
        "width": "720",
        "height": "1140"
    },
    {
        "id": "20509",
        "title": "Princess Fashion Rainbow Hairstyle Design",
        "description": "Do you like rainbows? A Rainbow is a symbol of beauty and many girls like it. They like to try rainbow eyeshadow, rain dress, and so on. Today our fashion girl Sofia wants to try a rainbow hairstyle. It's a good idea, right? Choose your favorite hairstyle to design. Have fun!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/o77epeeloj41gwa2kkzm44ot60j1srt3/",
        "category": "Hypercasual",
        "tags": "Design, Fun, Girl, Girls, H5, Hair, HTML5, Kid, Kids, Makeover, Princess",
        "thumb": "https://img.gamemonetize.com/o77epeeloj41gwa2kkzm44ot60j1srt3/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "20491",
        "title": "Snowball.io Game",
        "description": "Snowball.io is a very interesting leisure, competitive game. You can control your character to participate in the snowball war by sliding the screen with your fingertips. Scroll in the scene for a longer time to accumulate larger snowballs, and try to eliminate all your opponents. The whole process of the game is a great test of the player's finger flexibility. The simple snow-white painting style is also great. The operation is simple and easy to use. It is very suitable for boring times to kill the time!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/jdxrwawd43ij64lixz02uwhqnzmfjk2k/",
        "category": "3D",
        "tags": "Arena, Avoid, Boys, Fighting, Kids, Skills",
        "thumb": "https://img.gamemonetize.com/jdxrwawd43ij64lixz02uwhqnzmfjk2k/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20489",
        "title": "Princess Punk Fashion - Tattoo Desgin",
        "description": "Punk is a popular style among teenagers. It represents rock culture. Now Elsa and other princesses want to experience it. First, draw a tattoo on their arm. It is so cool. Then find suits and makeup to match it! They will be the coolest sisters on the road!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/svvtup32pi8yn8ycwusat9md0ce6v5xr/",
        "category": "Hypercasual",
        "tags": "Design, Dress Up, Fashion, Fun, Girl, Girls, H5, HTML5, Kid, Kids, Makeover, Princess",
        "thumb": "https://img.gamemonetize.com/svvtup32pi8yn8ycwusat9md0ce6v5xr/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "20485",
        "title": "Hero Tower Wars Online",
        "description": "Have fun with this entertaining action game, adventure Hero Tower Wars Online is an exclusive game of the tower defense category, help the little hero to bring down the towers in each of the levels!!! Enjoy this game in kiz10 for free and improve your score. A brave hero decided to attack the towers where her beautiful princess is trapped and needs you to free her from the clutches of different enemies. Move the character in each level of the tower calculates the addition, subtraction or multiplication to raise your level and defeat each enemy. try to obtain the different objects to increase your level, these will add many coins with which you can unlock different skins. Features:Adventure game, action, fights, tower defense.Complete each level and improve your score.Improve your character with each of the skins.Calculate addition, subtraction and multiplication.",
        "instructions": "Instructions Use the mouse right click to move the character on the towers On mobile devices and tablets touch and drag the character on each tower ",
        "url": "https://html5.gamemonetize.com/s2t7a2ugveaswq9el4ijblxtgeuwn8v7/",
        "category": "Adventure",
        "tags": "Casual, Fighting, kiz10, Tower Defense",
        "thumb": "https://img.gamemonetize.com/s2t7a2ugveaswq9el4ijblxtgeuwn8v7/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20426",
        "title": "Puzzle Parking 3D Game",
        "description": "Are you talented in parking the car? Puzzle Parking 3D is a good place to show your talent. You need to play as a car driver who needs to guide all cars in the parking space without any touching and crash. Train your brain and challenge yourself. You will become the next parking master. It's time to prove that you are a competent driver. You need to think before you move, some levels really need your brain, don't give up, keep trying and have fun!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/q30ld8k162b62hxiq2tvv58af1p8hcq1/",
        "category": "3D",
        "tags": "Avoid, Boys, Car, Driving, Kids, Parking, Puzzle, Skills, Strategy",
        "thumb": "https://img.gamemonetize.com/q30ld8k162b62hxiq2tvv58af1p8hcq1/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20397",
        "title": "Mr noob Jailbreak",
        "description": "Have fun with this entertaining new game Mr noob Jailbreak try to escape from the prison guards and go as far as possible with the best score, jump, slide and shoot the enemy guards and weapons !! You can play it for free on kiz10 and enjoy many other new games. A brave little noob decided to escape from prison, run through the roofs of the buildings and try to get as far as possible, but he ran into many guards and potential enemies that will eliminate you if you don't react quickly. Control the movements of the little noob to go far with the best score jump, shoot use the slowmotion to improve your aim. Have fun with this casual game and many others for free. KEY FEATURESFeatures: Adventure game, action and shooting. Casual jump and shoot game Minecraft based game You can play it on PC, Tablets and mobiles",
        "instructions": "Instructions Right click to shoot use the W key to jump S to slide and spacebar to use slowmotion On mobile devices and tablets use the touch game buttons ",
        "url": "https://html5.gamemonetize.com/aghhqhf3kc5px6s55hyg2igj5f9pc5za/",
        "category": "Hypercasual",
        "tags": "kiz10, running, Shooting, weapons",
        "thumb": "https://img.gamemonetize.com/aghhqhf3kc5px6s55hyg2igj5f9pc5za/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20392",
        "title": "Rotate Bridge 3D",
        "description": "Build bridges to save the trapped people! Rotate Bridge 3D is a casual puzzle game where you can build bridges. The more characters rescued, the more points and rewards you will eventually get. Build the bridge on a platform on the ground, not in a cave or on the sea. are you ready? Come on, the rescue mission begins!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/w46hfukyhxmuwb1uuel3gyzqrmrxkqvu/",
        "category": "Boys",
        "tags": "3D, 3D Games, Boy, Boys, Brain, Fun, H5, HTML5, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/w46hfukyhxmuwb1uuel3gyzqrmrxkqvu/512x384.jpg",
        "width": "640",
        "height": "1136"
    },
    {
        "id": "20391",
        "title": "Star Art - Art Game",
        "description": "Art has not only the power to inspire, but it can also be incredibly relaxing. Breathe deep, clear your mind, and unwind with this ultra-relaxing and endlessly enjoyable puzzle game guaranteed to relieve stress, soothe frayed nerves, prompt ASMR and promote mental wellness.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/3rmig7tze8ay3mst0fxforz1ikzmcs82/",
        "category": "Girls",
        "tags": "Boy, Boys, Color, Coloring, Creation, Design, Draw, Drawing, Fun, Girl, Girls, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/3rmig7tze8ay3mst0fxforz1ikzmcs82/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "20390",
        "title": "Pencil Rush 3D Game Online ",
        "description": "Can you imagine that a pencil can also run? In the game Pencil Rush Online, you will have the opportunity to control colored pencils. This is a 3D game with addictive gameplay. Your task is to complete all running routes with pencils, collect colored pencils on the platform and avoid obstacles. Objects, when you are about to reach the end, don't forget to complete a beautiful painting. It is worth noting that if you accidentally run into any obstacles, the number of your brushes will decrease. Are you ready?",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/ahtlfdsyxel89x6mmj3uey6xou3h72og/",
        "category": "Boys",
        "tags": "3D, 3D Games, Boy, Boys, Draw, Fun, H5, HTML5, Kid, Kids, Race, run",
        "thumb": "https://img.gamemonetize.com/ahtlfdsyxel89x6mmj3uey6xou3h72og/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20389",
        "title": "Bulldozer Crash Race - Mad 3D Racing Game",
        "description": "Bulldozer is a very important large-scale mechanical equipment. In many construction sites and mines, bulldozers are essential and important equipment, and they are used for ore mining. A bulldozer is a kind of earthwork machinery capable of excavating, transporting, and discharging rock and soil. Today, in the game Bulldozer Crash Race, you will have the opportunity to drive this heavy equipment and drive the bulldozer to a designated position. Are you ready?",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/vorhdghwz5j6sg8djron45mdclm1oe6e/",
        "category": "Racing",
        "tags": "3D, Action, Boy, Boys, Car, Fun, H5, HTML5, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/vorhdghwz5j6sg8djron45mdclm1oe6e/512x384.jpg",
        "width": "1334",
        "height": "750"
    },
    {
        "id": "20346",
        "title": "Traffic Racer King",
        "description": "Traffic Racer King is undoubtedly one of the most interesting new arcade games this year, with the 3D art style and addictive simulation of real gameplay. If you are a driving game lover, don't miss this game! In the game, you will no longer be restricted by traffic rules, and you don't have to worry about traffic lights. You can enjoy the flying speed and special acceleration function. Whenever the charging button changes color, you can use the acceleration function to surpass others. For all vehicles, you don't have to worry about time.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/1wndvhs7phy774b3ag3tk2bk12fu2kkx/",
        "category": "Racing",
        "tags": "3D, 3D Games, Boy, Boys, drift, drifting, Fun, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/1wndvhs7phy774b3ag3tk2bk12fu2kkx/512x384.jpg",
        "width": "1334",
        "height": "750"
    },
    {
        "id": "20345",
        "title": "Drifty Race - 3D Drifting Game",
        "description": "Click to drift, release to go straight. Pass the curves, and obstacles, sprint with the help of acceleration bands, win the trophy, and unlock more advanced racing cars! Win the competitions, operate your own Car Shop, and the crazy drifting game Drifty Race is waiting for your coming!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/jqhn0n0yansb75cboen1ipwnlqmzciuj/",
        "category": "Racing",
        "tags": "3D, 3D Games, Boy, Boys, drift, drifting, Fun, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/jqhn0n0yansb75cboen1ipwnlqmzciuj/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20315",
        "title": "Archer Hunter King Game",
        "description": "Archer Hunter King is a fun confrontation arcade game. There are two modes for you to choose from, you can either choose the parkour hunting mode or the endless breakout mode. In parkour hunting mode, you need to survive to the end with your skills within the time limit. In the endless mode, you need to protect the king, if the king dies you will also fail. You can use the reward for passing to unlock new characters and skills. Start when you're ready! Just waiting for you! Have fun!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/18zw26gccalbo5fsbt5vbiqfm336m2zu/",
        "category": "3D",
        "tags": "3D, Arcade, Avoid, Boys, Collecting, Flight, Kids, Killing, Obstacle, running, Skills, Timing",
        "thumb": "https://img.gamemonetize.com/18zw26gccalbo5fsbt5vbiqfm336m2zu/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20314",
        "title": "Fruit Sort Puzzle - Color Puzzle",
        "description": "What flavor of candy cane do you like to eat? Come and join Fruit Sort Puzzle to make your own candy cane to suit your taste! Move the fruits, three or more of them can be combined and upgraded, and finally, you have to target the hawthorn. If the fruit exceeds the maximum limit of the fork, you will fail. Can you successfully make hawthorn candy canes? Believe in yourself! Have fun!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/fy4bix8fmtwb373cniwofov5cmj1qtjh/",
        "category": "Puzzles",
        "tags": "2D, Boy, Boys, Educational, Fun, Girl, Girls, H5, HTML5, Kid, Kids, Puzzle",
        "thumb": "https://img.gamemonetize.com/fy4bix8fmtwb373cniwofov5cmj1qtjh/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20313",
        "title": "Phone Case DIY 2 - Casetify Game",
        "description": "Do you have artistic talent? If you are not sure about your artistic talent. The newly released Phone Case DIY game can help you discover it. The pretty girl wants to attend her sister's party and she needs you to design the latest phone case for her. We picked many beautiful colors, stickers, and phone case models for you. We have also prepared 3 different making processes for you: By choosing Stencil art, you can spray lots of pretty patterns on the phone case. By choosing Pop it, you will enjoy the fun of Pop it...Trust us, no matter what color you spray on the phone case and what making processes you choose, it always comes out pretty. Come and play this game to find more fun stuff!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/chqus7dya051pc02snslpsl5448f4d99/",
        "category": "Girls",
        "tags": "Craft, Crafting, Creation, Design, Educational, Fun, Girl, Girls, H5, HTML5, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/chqus7dya051pc02snslpsl5448f4d99/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "20280",
        "title": "Block Stacking 3D Game",
        "description": "Block Stacking is a very fun, leisure, and pressure-relieving game. The game is very delicate and fresh. In the game, you will play by combining many different fruits. As long as you can complete the target tasks, you will have a chance to get rewards! By eliminating the fruits on the screen, you can successfully pass the level. It's extremely easy to operate, which makes you feel very addicted. Come and try the game!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/phqz51ly7300bw16gwvmreop5i8gkhi3/",
        "category": "3D",
        "tags": "Boys, Cute, Girls, Hypercasual, Kids, Puzzle",
        "thumb": "https://img.gamemonetize.com/phqz51ly7300bw16gwvmreop5i8gkhi3/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20277",
        "title": "Prison Noob vs Pro",
        "description": "Everyone's favorite noob is trying to escape from prison and escapes from prison with his pro friend accompanying him. two boys noob and pro who escaped from prison never stop. Noob and pro, who are very happy that they escaped from the prison, first collect the diamonds, then open the secret doors and run to the elevator. Noob and pro, sneaking under the ground, finally reach the elevator.And don't forget that the water is slowly rising as the snow melts. Get to the elevator ahead of time!",
        "instructions": " Move to WASD Arrow Keys Double Jump available Mobile Touch Control Only noob can collect diamonds Only Pro can open doors ",
        "url": "https://html5.gamemonetize.com/meyzgl3dm7e5cif1nezidw2mp4iadnaq/",
        "category": "Adventure",
        "tags": "2 Player, 2 Player Games, 2D, Adventure, Arcade",
        "thumb": "https://img.gamemonetize.com/meyzgl3dm7e5cif1nezidw2mp4iadnaq/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20243",
        "title": "Ultimate Robo Duel 3D",
        "description": "In the Ultimate Robo Duel 3D game, you can fight in the arena with advanced robots. You will feel yourself in the arena with its realistic sounds, effects and atmosphere! You can play the game against the computer or against your friend in 2 PLAYER mode!",
        "instructions": "PLAYER 1 Move W A S D Punch F G Special Hit H Bullet T Kick C V Grab Move B PLAYER 2 Move ARROW KEYS Punch U I Special Hit O Bullet M Kick J K Grab Move L ",
        "url": "https://html5.gamemonetize.com/jtxkx8m8d4gxy86tqqbfou2ni2i7qgsi/",
        "category": "Action",
        "tags": "2 Player, 2 Player Games, Battle, Fight, Fighting, Monster, Robot, War",
        "thumb": "https://img.gamemonetize.com/jtxkx8m8d4gxy86tqqbfou2ni2i7qgsi/512x384.jpg",
        "width": "800",
        "height": "450"
    },
    {
        "id": "20241",
        "title": "Martial Arts: Fighter Duel",
        "description": "Welcome to the duel tournament of martial arts! 17 martial arts masters from different countries and geographies meet in the arena. Show your unique fighting style and try to beat the opponents. You can join the tournament in &quot;Arcade&quot; mode or you can compete with your friend in &quot;2 Player&quot; mode. You can set the difficulty level of the game in the settings section. If you are ready for fights, you can start.",
        "instructions": "PLAYER 1 MOVE W A S D PUNCHES F G H KICKS C V B PLAYER 2 MOVE ARROW KEYS PUNCHES U I O KICKS J K L ",
        "url": "https://html5.gamemonetize.com/fkufwp79zlik99606k8riro79ri461lw/",
        "category": "Action",
        "tags": "2 Player, 2 Player Games, 3D, Battle, Fight, Fighting, Street Fighting",
        "thumb": "https://img.gamemonetize.com/fkufwp79zlik99606k8riro79ri461lw/512x384.jpg",
        "width": "800",
        "height": "450"
    },
    {
        "id": "20237",
        "title": "Real Excavator Simulator Game",
        "description": "Real Excavator Simulator is an online Boy game. We have some construction missions on this town in a 3D construction vehicle driving simulation game called Real Excavator Simulator. Your target is to drive several kinds of construction vehicles including trucks and excavators to arrive at the marked areas and complete simple construction works. Have a good time!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/stnjsz9tkk98f02ul6kyhmcrhrv4c5cr/",
        "category": "3D",
        "tags": "Boys, Kids, Puzzle, Strategy",
        "thumb": "https://img.gamemonetize.com/stnjsz9tkk98f02ul6kyhmcrhrv4c5cr/512x384.jpg",
        "width": "1334",
        "height": "750"
    },
    {
        "id": "20232",
        "title": "Nitro Knights.io - Strategy Fighting Game",
        "description": "Nitro Knights.io is undoubtedly one of the most interesting multiplayer online battle games this year, with addictive gameplay and a 2D art style. If you are a lover of IO games, don't miss this game! Vigorously triumph in lance battles between futuristic knights in hyperspace. Beat all the levels! Equip the best hovercraft and lance your way to victory! Are you ready? If you like this game, don't forget to share it with your friends!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/u6euldk5mipqphq3gd35t37vuhmlb9t7/",
        "category": "Action",
        "tags": ".io, .io Games, Aircraft, Boy, Boys, Fight, Fighting, Fun, Kid, Kids, Multiplayer",
        "thumb": "https://img.gamemonetize.com/u6euldk5mipqphq3gd35t37vuhmlb9t7/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20229",
        "title": "NERF Epic Pranks - Prank &amp; Run",
        "description": "In this cool 3D funny game NERF Epic Pranks, players will use guns to trick people in different worlds. Players also need to be careful not to be found by the enemy while playing tricks. Unlock more skins using your coins. Have fun in this interesting game NERF Epic Pranks!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/qx9tyrn2r22yia8zom3j3rss9ysoj17j/",
        "category": "Hypercasual",
        "tags": "3D, 3D Games, Boy, Boys, Fun, Funny, Girl, Girls, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/qx9tyrn2r22yia8zom3j3rss9ysoj17j/512x384.jpg",
        "width": "640",
        "height": "1368"
    },
    {
        "id": "20228",
        "title": "Saw Machine.io - 3D Survival Game",
        "description": "Saw Machine.io is an exhilarating casual game. It will not be exaggerating to say that human history is somehow a history full of suppression, vividly demonstrating the principle of survival of the fittest. In this game, similar rules apply. Ruthlessness is the key to survival. Initially serving as a tool with a long blade with sharp points or teeth along with one of its edges, a saw will turn into a deadly weapon. The velocity of the vehicle carrying the saw will enhance its lethality to an unimaginable extent!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/mh2w49xb539wnjgu6d808liynzner1ny/",
        "category": "3D",
        "tags": ".io, .io Games, 3D, 3D Games, Action, Boy, Boys, Fun, Kid, Kids, Machine",
        "thumb": "https://img.gamemonetize.com/mh2w49xb539wnjgu6d808liynzner1ny/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20227",
        "title": "Party.io - 3D Survival Game",
        "description": "Party.io is an addicting 3D multiplayer arena game. In the game, players need to control their character to fight with other players. You need to throw all your opponents down. The more people you throw, the higher score you will get. Come on, it's not an easy game, try to get a high rank on the Party.io!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/9j0mf9y3942pekpu2phm9tfj1ou8u3mk/",
        "category": "3D",
        "tags": ".io, .io Games, 3D, 3D Games, Action, Boy, Boys, Fun, Kid, Kids, Kill, Killing",
        "thumb": "https://img.gamemonetize.com/9j0mf9y3942pekpu2phm9tfj1ou8u3mk/512x384.jpg",
        "width": "720",
        "height": "1360"
    },
    {
        "id": "20226",
        "title": "Fish Parking - Parking Master",
        "description": "Welcome to the new era of car parking games. In Fish Parking, you will experience the free-to-play real parking game, real ground, familiar roadblocks, clear steering wheel, and accelerator, brake buttons, making you immersive and easy to use. We need to drive a car on a road full of obstacles. We must pay attention to avoid obstacles and reach the end to pass. Let us experience it together now.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/lecaawhe31r5glidcg9t6aycu2neuvby/",
        "category": "Boys",
        "tags": "3D, 3D Games, Boy, Boys, Car, Fun, H5, HTML5, Kid, Kids, Parking",
        "thumb": "https://img.gamemonetize.com/lecaawhe31r5glidcg9t6aycu2neuvby/512x384.jpg",
        "width": "1334",
        "height": "750"
    },
    {
        "id": "20225",
        "title": "Cristiano Ronaldo Kick N Run",
        "description": "Super soccer star Cristiano Ronaldo is going to start an exciting adventure. He will run all the way with a soccer ball. Avoid obstacles. After you collect four letters, you will pass successfully. Attention other players, they are foxy, they will change direction.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/spgx5ytd64fptcz6od43gzyyfsottpi8/",
        "category": "Soccer",
        "tags": "3D, 3D Games, Boy, Boys, Football, Fun, H5, HTML5, Kid, Kids, Soccer, Sport, Sports",
        "thumb": "https://img.gamemonetize.com/spgx5ytd64fptcz6od43gzyyfsottpi8/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20224",
        "title": "3D Stacky Dash Craft Run",
        "description": "Stacky Run is an interesting new arcade game, but also a rare 3D art-style parkour game. Your job is to control the parkour stickman between the different platforms in the game. It is worth remembering that the path is made of bricks for running. To run between various platforms, you must gather enough bricks. Don't forget to collect purple gems, fly through time, and wish you the first to hit the end! You cannot get through the water if you don't have enough bricks. Collect more bricks on the last island you will walk on. So many diamonds are waiting for you there!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/iv9s3ki1zdk0jgyn5juuiugnk3jrkmno/",
        "category": "Boys",
        "tags": "3D, 3D Games, Boy, Boys, Craft, Fun, H5, HTML5, Kid, Kids, run, running, Stack",
        "thumb": "https://img.gamemonetize.com/iv9s3ki1zdk0jgyn5juuiugnk3jrkmno/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20175",
        "title": "Water Flow Puzzle Game",
        "description": "Water Flow Puzzle is an online Boy game. Water Flow Puzzle plays like a pipe-connection puzzle game with 3D arcade cute cartoon green plants and rotatable pipes. It is managed for you to help the green plant by means of rotating the direction of pipes and making a path for water to rescue it! There are no time limitations here for all levels. Keep calm and have a good time!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/88s6bn1zjqlib883qbnzt0v8xxhnuxo4/",
        "category": "3D",
        "tags": "Boys, Cute, Fire, Girls, Hypercasual, Kids, Puzzle",
        "thumb": "https://img.gamemonetize.com/88s6bn1zjqlib883qbnzt0v8xxhnuxo4/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20174",
        "title": "Fit And Squezze",
        "description": "Ball filling is an interesting puzzle game. Players need to use a number of different sizes of the ball, it will be filled into the level of different shapes of the bottle, all the balls in the game will be filled into the bottle, but can not overflow the dotted line requirements. Don't you want to challenge it?",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/czfds0s3ts51mf4xlpiluabcrkawqjcu/",
        "category": "Girls",
        "tags": "Boy, Boys, Brain, Fun, Funny, Girl, Girls, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/czfds0s3ts51mf4xlpiluabcrkawqjcu/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20173",
        "title": "Ultimate Flying Car",
        "description": "Do you want to take fast rides and flights on the long streets of the city? Ultimate Flying Car game invites you to realistic flying car simulator experience. Explore the sky with stylish flying cars, or unlock new cars by participating in races. You can play all of these game modes either 1 player or 2 player.",
        "instructions": "Player 1 Move W A S D NOS SHIFT Look back T Fix car s position R Handbrake SPACE Player 2 Move ARROW KEYS NOS M Look back L Fix car s position U Handbrake K ",
        "url": "https://html5.gamemonetize.com/yqbipdebtjz8q97zamh7utwjdrs1bh1e/",
        "category": "Racing",
        "tags": "2 Player, 2 Player Games, Driving, Flight, fly, Racing, Stunts, Supercars",
        "thumb": "https://img.gamemonetize.com/yqbipdebtjz8q97zamh7utwjdrs1bh1e/512x384.jpg",
        "width": "800",
        "height": "450"
    },
    {
        "id": "20171",
        "title": "Jelly Dye Game",
        "description": "Filling in color in jelly slimes is so decompressing and fun. After a tiring day of study and work, just come home to play this game, Jelly Dye, at night, and all the fatigue will disappear. Each level has the shape sculpted for you, pick up the colors in a logical order with a straw, and reinject the appropriate modules. Let it go back to its original color for a beautiful finish. While enjoying beautiful colors, use your spatial imagination and think about color combinations. It's fun and challenging to exercise and rest your brain at the same time. Come and try it",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/xymr15s0eu8hrh06mig6zsx6nalvfynb/",
        "category": "3D",
        "tags": "Boys, Brain, Kids, Puzzle, Simulation, Simulator, Skills",
        "thumb": "https://img.gamemonetize.com/xymr15s0eu8hrh06mig6zsx6nalvfynb/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20123",
        "title": "3D Moto Racing Challenge",
        "description": "Can you be number one in a multiplayer game Moto 3D Racing Challenge? Prepare for the ultimate moto racing challenge game. You need to practice your car skills before all the riders are beaten. Surprise motorcycles are waiting to be got by you. Pay attention to the blue arrow on the road that will make you speed up and enter a temporary invincible state. Whether or not you are a racing master, the answer can be known in the final line.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/owd31adel5gn4vswnxcn1wnxg8io3csg/",
        "category": "Racing",
        "tags": "3D, 3D Games, Action, Boy, Boys, Fun, Kid, Kids, Moto, Motorcycle, Race, Racing",
        "thumb": "https://img.gamemonetize.com/owd31adel5gn4vswnxcn1wnxg8io3csg/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20122",
        "title": "Drift At Will - Crazy 3D Drifting Game",
        "description": "Drift At Will is an engrossing casual game. If the excitement at the mere glimpse of a race can as a matter of fact get the level of adrenalin inside your body soaring, you really need to try this game. The rapid turning of directions might be a little bit overwhelming at the very start, but as time goes by, you will master the control and fall in love with drifting unceasingly as quick as flash on the wide road.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/gq4egtu93ym7t2tlo9oxz9gujaslznqk/",
        "category": "Racing",
        "tags": "3D, 3D Games, Bike, Boy, Boys, drift, drifting, Driving, Fun, H5, HTML5, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/gq4egtu93ym7t2tlo9oxz9gujaslznqk/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20120",
        "title": "Super Friday Night Funkin Vs Noobs",
        "description": "Have fun with this new game Friday Night Funkin vs Noob 'a new game in this fabulous saga !! Play the ritual of each music with your favorite minecraft characters and press the game buttons at the right time and accumulate the points to show that you are the best.The objective of the game is to complete the levels without missing the movements of each music, touch the buttons at the right time and accumulate your best score complete the musical themes.",
        "instructions": "Instructions Play with the mouse and keyboard arrows on pc to follow the movements On mobile devices touch the sectors of the screen that correspond to the movements ",
        "url": "https://html5.gamemonetize.com/5yawlik7r2nzbin770okmjjizpwaz10e/",
        "category": "Hypercasual",
        "tags": "Casual, kiz10, Minecraft, Music",
        "thumb": "https://img.gamemonetize.com/5yawlik7r2nzbin770okmjjizpwaz10e/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20118",
        "title": "Mini War Clash Z",
        "description": "The objective of the game is to complete each level in a war of strategic movements, move your troops to arrive with the number of soldiers necessary to capture the enemy base. Decide your movements by counting the sum of soldiers of each movement to eliminate the soldiers positioned at different points of your base. Features:Strategy and war game.Control when to shoot your enemies.Learn to add to get to the enemy commandos.Action and shooting game you will need to calculate your movements.",
        "instructions": "Instructions Use the right mouse Right click to play and control your soldiers On mobile devices touch the screen and the UI buttons of the game ",
        "url": "https://html5.gamemonetize.com/40k8j56x3pulgeryv9jnmhxgtxze2sdx/",
        "category": "Hypercasual",
        "tags": "Gun, kiz10, Shooting, Strategy, War",
        "thumb": "https://img.gamemonetize.com/40k8j56x3pulgeryv9jnmhxgtxze2sdx/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "20083",
        "title": "Street Mayhem: Beat Em Up",
        "description": "Street Mayhem - Beat 'Em Up game invites you to a long adventure. You struggle with bad guys and mutants in different places. You are accompanied by Edward, Jennifer and Russell in this fight. Each character has different abilities and style. You need to score to unlock the characters Russell and Jennifer. Try to complete the game story by fighting in Dark City, Forest, City Town and the final episode Castle. In the other mode of the game, in the 2 PLAYER section, you can have classic fights with your friend. Whoever wins 3 Rounds wins the game!",
        "instructions": "PLAYER 1 Move W A S D or ARROW KEYS Arrow keys are only active in Story Mode Jump SPACE Attack F G Defend H PLAYER 2 Move W A S D or ARROW KEYS Jump L Attack P O Defend I ",
        "url": "https://html5.gamemonetize.com/47lce5e4kb51icu8gbckm8x39aiztmuf/",
        "category": "Action",
        "tags": "2 Player, 2 Player Games, Adventure, Battle, Fight, Fighting, Street Fighting",
        "thumb": "https://img.gamemonetize.com/47lce5e4kb51icu8gbckm8x39aiztmuf/512x384.jpg",
        "width": "800",
        "height": "450"
    },
    {
        "id": "20076",
        "title": "Clown Park Hide And Seek Game",
        "description": "Clown Park - Hide And Seek is a camp against camp arcade game. It has beautiful graphic design and 3D space design. There are three modes for you to choose from Survivor camp, Chaser camp, or if you have trouble choosing or want a little excitement, you can choose any mode and it will randomly choose the lineup. Survivors need to collect enough keys to open the escape door within the time limit and escape successfully to win. On the contrary, the pursuer is to stop the survivor's pace. A variety of cool skins and skills are waiting for you to unlock! Complete the missions to unlock the characters! Have fun!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/pylvaxzq54f5lwghdqonah3tayx1qxxd/",
        "category": "3D",
        "tags": "3D, Arcade, Avoid, Boys, Collecting, Escape, Flight, Funny, Kids, Killing, Obstacle, running, Skills, Timing",
        "thumb": "https://img.gamemonetize.com/pylvaxzq54f5lwghdqonah3tayx1qxxd/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20071",
        "title": "Crazy Racing Master",
        "description": "Crazy Racing Master is a car racing game. You will race with other cars. Keep sure you will not rush out of the track. And there are kinds of props you can use, also you will be used. Finishing the race is a big step for you. Take it slowly.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/8dw7xmp9amayym8nuhw4209pig32ukf8/",
        "category": "Racing",
        "tags": "3D, 3D Games, Action, Boy, Boys, Car, drift, drifting, Driving, Fun, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/8dw7xmp9amayym8nuhw4209pig32ukf8/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20070",
        "title": "Shinecool Stunt Motorbike - Moto Racing",
        "description": "A pure motorbike race is a little boring, let us add some different exciting elements. Battle, rocket, bomb, pan. You could kick and attack others! Kill your opponents is so cool. Also, you could be attacked too, avoid that and win the game!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/oeexjg469kbc65jq8wiwan8i3mqp6k37/",
        "category": "Racing",
        "tags": "3D, 3D Games, Boy, Boys, Fun, Kid, Kids, Moto, Motorcycle, Race, Racing",
        "thumb": "https://img.gamemonetize.com/oeexjg469kbc65jq8wiwan8i3mqp6k37/512x384.jpg",
        "width": "1334",
        "height": "750"
    },
    {
        "id": "20060",
        "title": "Match To Paint Game",
        "description": "Match To Paint is an interesting game that mixed match elements and painting elements. In a limited number of steps, you only need to click two squares of the same color to eliminate them directly, and the beautiful 3D game graphics bring you the best game experience. This is a big competition of brainpower, will you accept the challenge? Come on, join us and show your game talent in the game Match To Paint!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/ejc7qtqyqj9ckxyk4awlw77q0rucgo4r/",
        "category": "Boys",
        "tags": "3D, Boys, Brain, H5, Kids, Puzzle, Skill, Strategy",
        "thumb": "https://img.gamemonetize.com/ejc7qtqyqj9ckxyk4awlw77q0rucgo4r/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "20028",
        "title": "Kill The Monster Game",
        "description": "Welcome to kill The Monster! kill The Monster is a fun beat-em-up arcade game. Collect gold coins by having more amount of glass. Watch out for spikes, pink object obstacles, and every time you pass a pink object you will reduce the corresponding amount of energy. The more energy you have at the end, the more likely you are to defeat the monster! Gold coins can be used to unlock new skins. Come join us, more cool skins are waiting for you! Have fun!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/qij756o0jte693nwgseo0y7xv9viyoz3/",
        "category": "3D",
        "tags": "3D, Avoid, Boys, Collecting, Flight, Kids, Obstacle, Platform, running",
        "thumb": "https://img.gamemonetize.com/qij756o0jte693nwgseo0y7xv9viyoz3/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "20019",
        "title": "Car Master 3D",
        "description": "Car Master 3D is a candy-paint-style driving game. You are going to start a steeplechase. Driving the car to pass through the moving obstacles. Collect coins to buy cool cars. You could drive carefully, but have to finish in time.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/8euguy6n677497qy4t54bhipdvf7jnic/",
        "category": "Racing",
        "tags": "Boy, Boys, Car, drift, drifting, Driving, Fun, H5, HTML5, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/8euguy6n677497qy4t54bhipdvf7jnic/512x384.jpg",
        "width": "1334",
        "height": "750"
    },
    {
        "id": "20018",
        "title": "Kids Cars Game Online",
        "description": "Kids Cars Games is a fun educational game suitable for preschoolers. It can help children learn the names of various parts of vehicles, including rescue vehicles, agricultural equipment, construction vehicles and military vehicles. There are even cranes, excavators, tractors, and harvesters. It is worth noting that children not only need to clean some military equipment, but also need to repair them, including tanks and warships. This game can cultivate children's logical thinking and imagination.",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/2n7exc5eofolojlxc1spthfjujm0s0po/",
        "category": "Boys",
        "tags": "Boys, Car, Cute, Educational, Girls, Kids, Matching, Simulation",
        "thumb": "https://img.gamemonetize.com/2n7exc5eofolojlxc1spthfjujm0s0po/512x384.jpg",
        "width": "800",
        "height": "504"
    },
    {
        "id": "20006",
        "title": "Farmers.io",
        "description": "Farmers.io is an interesting multiplayer relaxing game in which you can compete with other players. You will drive a truck and collect crops. The more crops you collect, the longer you will become. Avoid other trucks, if you crash into them, you will lose. Try to get the first place to enter the next level. You will unlock more cars when you pass a certain number of levels. Have a good time in our new game Farmers.io!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/yt7e8qx4za8r805j6i5gwsyzccmf7xi2/",
        "category": "3D",
        "tags": ".io, .io Games, 3D, 3D Games, Boy, Boys, Fun, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/yt7e8qx4za8r805j6i5gwsyzccmf7xi2/512x384.jpg",
        "width": "1080",
        "height": "1920"
    },
    {
        "id": "19972",
        "title": "Mr Noob Pro Archer",
        "description": "Have fun with this new action game Mr Noob Pro Archer is an archery game where the little noob must shoot his arrows at the enemies that arrive to eliminate you !!! Can you help eliminate with your bow and arrow? Try it on kiz10 totally free. One day like another, a little noob will meet multiple enemies who want to eliminate you, they will not hesitate to hurt you with their arrows or swords, can you stop them? This is a new game where the little noob archer must eliminate the enemies with his bow and arrow!! Objectives Eliminate all the enemies that will be located in different positions of the levels, improve your score with each elimination, collect all the gold you can, try as many times as you want and enjoy a casual action game.",
        "instructions": "Instructions Aim and shoot with the mouse right click on PCOn mobile and tablet devices touch the screen to aim and release to shoot ",
        "url": "https://html5.gamemonetize.com/4czbh2hebirs7du5a5s1dy9gkwnma3ea/",
        "category": "Arcade",
        "tags": "Hypercasual, kiz10, Minecraft, Shoot",
        "thumb": "https://img.gamemonetize.com/4czbh2hebirs7du5a5s1dy9gkwnma3ea/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "19965",
        "title": "Hill Dash Car - Hill Climbing Racing Game",
        "description": "Race to the finish line over a multitude of racing tracks with hazards, hill climbs, jumps, loops, bridges, and ramps. Go turbo with awesome truck upgrades and try to climb to the top of the leaderboard in this crazy racing game Hill Dash Car that will test your driving skills to the limit!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/u3m65yzhs2dxuzhp28h3dqzzz02efggj/",
        "category": "Action",
        "tags": "3D, 3D Games, Car, Driving, Fun, Kid, Kids, Race, Racing",
        "thumb": "https://img.gamemonetize.com/u3m65yzhs2dxuzhp28h3dqzzz02efggj/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19935",
        "title": "Craft Island 3D Game",
        "description": "Welcome to Craft Island! It is a new Idle game in which players have fun logging and building with unique landscapes while becoming rich island craft owners.. You need to build buildings by cutting down trees. Stores, rings, and other buildings need to be unlocked by your efforts. After unlocking the rings, you can enter Breakout mode and build your own weapons camp by collecting trees. You can choose any archer or artillery soldier. Are you ready to declare your victory? Enjoy!",
        "instructions": "",
        "url": "https://html5.gamemonetize.com/46kpfecieeb3ao2iyykpp29wvxftotn1/",
        "category": "Boys",
        "tags": "3D, Arcade, Avoid, Boys, Collecting, H5, Kids, Killing, Skills, Street Fighting, War",
        "thumb": "https://img.gamemonetize.com/46kpfecieeb3ao2iyykpp29wvxftotn1/512x384.jpg",
        "width": "1080",
        "height": "1920"
    },
    {
        "id": "19932",
        "title": "Super Tornado.io - Tornado Rush",
        "description": "A powerful tornado can destroy everything! Especially the water tornado formed from the sea. In Super Tornado.io this multiplayer online game, you will become the master of the world. You can control the city by the sea at will, blow away all the buildings and cars, and compete with other players. Tornadoes fight, swallow them and absorb them as part of your own power. When you have enough power, don't be afraid of any other players, use tornadoes to rule the world until you are satisfied.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/kdrph2e3tzo27kl1jhz1ays9urs7ib16/",
        "category": "3D",
        "tags": ".io, .io Games, 3D, 3D Games, Battle, Boy, Boys, Fight, Fun, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/kdrph2e3tzo27kl1jhz1ays9urs7ib16/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "19931",
        "title": "Animal.io - 3D Animal Warfare",
        "description": "Animal.io is an interesting multiplayer online game. Control your animal to push others off the platform by swinging your tail. Meat can increase your size and hamburger can add the length of the tail, the mushroom will become little size but faster. Kill your enemies and win the game! To unlock more adorable animals!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/ccox3h8gw8bzvvwbx7hnmnhzujb7lum4/",
        "category": "3D",
        "tags": ".io, .io Games, 3D, 3D Games, Action, Animal, Boy, Boys, Fun, H5, HTML5, Kid, Kids, War",
        "thumb": "https://img.gamemonetize.com/ccox3h8gw8bzvvwbx7hnmnhzujb7lum4/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19888",
        "title": "Count Master 3d Game",
        "description": "The arcade game Count Master 3d is a lot of fun. You will have to lead your people to rule the entire planet as a great leader. Let's begin by taking a few castles. To add soldiers, drag the formula below. To boost the offensive capability of your men, you can equip them with weapons. Are you prepared to take over the world? Come in and give it a shot!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/h29k7j1k1lteufdwei0ldn4enpkekk7r/",
        "category": "3D",
        "tags": "Arcade, Obstacle, Puzzle, run, War",
        "thumb": "https://img.gamemonetize.com/h29k7j1k1lteufdwei0ldn4enpkekk7r/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19875",
        "title": "Diy Keyboard Game",
        "description": "Diy Keyboard is a very unique art game. Have you ever thought about design your own style keyboards? Here is the game that can make you satisfied. Here you can experience 5 different manufacture methods: Resin, Acrylic, Pop it, Stencil and Decor. We also carefully prepared lots of beautiful ornamental for you. In our game, you have every opportunity to use your design and drawing talents. You can draw your keyboards to white, blue or red... You can also make your keyboard transparent if you like. Come and try this game! We are sure you will love it!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/7bn6wcfjuk3deuetqel6cp6keecskrwj/",
        "category": "Hypercasual",
        "tags": "Boys, Cute, Girls, Kids, Puzzle",
        "thumb": "https://img.gamemonetize.com/7bn6wcfjuk3deuetqel6cp6keecskrwj/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "19870",
        "title": "Idle Sheep 3d Game",
        "description": "Idle Sheep 3D is a business casual game. By feeding sheep and selling wool around the world, you can become the king of wool. Wool production can be used to earn and buy wool in idle money games. There are many idle games but tiny sheep idle wool simulator games are unusual because they set a noble goal of becoming rich. You can earn money by playing our simple clicker game. Make the richest idle business in idle wool tiny sheep game.",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/u3hhgz3g3e981n2pgj2o9z2rmkugeg7f/",
        "category": "3D",
        "tags": "Animal, Cute, Farm, Hypercasual, Kids, Puzzle, Shopping",
        "thumb": "https://img.gamemonetize.com/u3hhgz3g3e981n2pgj2o9z2rmkugeg7f/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19822",
        "title": "Doctor Pets - Be Vet and Help Animals",
        "description": "Doctor Pets brings you a great chance to make animals healthy and happy again. Nature is home to a playful motley crew of animals. Dogs, cats, rabbits, and monkeys are looking for your help in a forest pet hospital. They need a doctor's help and they need it right now!",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/trsiq22rc7bcu1qleztq8lo9djre00nm/",
        "category": "Hypercasual",
        "tags": "Animal, Cat, Doctor, Educational, Girl, Girls, H5, HTML5, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/trsiq22rc7bcu1qleztq8lo9djre00nm/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "19821",
        "title": "Doctor Kids 2 - Doctor Game",
        "description": "Check the respiratory system, fix sore throat problems, get rid of head lice, heal digestive problems, use a head MRI scan, or fly an emergency helicopter. Use your medical skills and spread a bit of happiness to your sick little patients.",
        "instructions": "Tap or click ",
        "url": "https://html5.gamemonetize.com/9cqnazvygopdztm0b5u3uf64k7o8soa6/",
        "category": "Hypercasual",
        "tags": "Doctor, Educational, Fun, Girl, Girls, H5, HTML5, Kid, Kids",
        "thumb": "https://img.gamemonetize.com/9cqnazvygopdztm0b5u3uf64k7o8soa6/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "19790",
        "title": "Desire IO",
        "description": "A dynamic multiplayer game with a first-person view! There are several game modes available for you to choose from that are suitable for all players. Unlock and upgrade fighters, complete tasks and compete with other players in tournaments!",
        "instructions": "Moving - WASD Shooting - Left mouse button Aiming - Right mouse button Changing weapons - Mouse Wheel Jump - Space Sit down - C Running - Shift to the left You can also change the controls in the game settings ",
        "url": "https://html5.gamemonetize.com/z6bxu09p77m6wa2ceb4nbd8s4i35ktiq/",
        "category": "Shooting",
        "tags": ".io, .io Games, 1 Player, 3D, 3D Games, Action, Battle, Boy, Boys, Fire, Game, Games, Girl, Girls, Multiplayer, Online, Shooter, Shooting",
        "thumb": "https://img.gamemonetize.com/z6bxu09p77m6wa2ceb4nbd8s4i35ktiq/512x384.jpg",
        "width": "1000",
        "height": "650"
    },
    {
        "id": "19788",
        "title": "Snack Rush Puzzle Game",
        "description": "Snack Rush Puzzle is a casual and puzzle online game, which is free for kids. This game is a combination of cartoon style and fun games. Your tasks are to eat a big meal, pass some obstacles on the way. You have to flexibly change the position, complete the series of challenges of the level, continuous clearance, at the end of each level. Come and challenge yourself here!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/mpew4y72k0feph85yeyz6wi50tubdkn3/",
        "category": "3D",
        "tags": "Boys, Food, Girls, Kids, Puzzle, running",
        "thumb": "https://img.gamemonetize.com/mpew4y72k0feph85yeyz6wi50tubdkn3/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19756",
        "title": "Tricky Track 3d 2 Game",
        "description": "Tricky Track 3D 2 is a fun confrontational parkour arcade game. At each level, you will be pitted against a human-machine and the victory belongs to the first participant to the finish line. When the road is green, you can pass. If it's red, you'll be blocked or slowed down. Watch out for the balls the other team throws at you! It will stop your progress! Doesn't that sound like fun?",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/9ju5mqq6v3rkdkxjl51z5n2yuev87wff/",
        "category": "3D",
        "tags": "Arcade, Avoid, Ball, Boys, Kids, Obstacle, Platform, Racing, running, Skills",
        "thumb": "https://img.gamemonetize.com/9ju5mqq6v3rkdkxjl51z5n2yuev87wff/512x384.jpg",
        "width": "720",
        "height": "1280"
    },
    {
        "id": "19755",
        "title": "Brutal Battle Royale 2",
        "description": "Brutal Battle Royale 2 features randomly generated battleground with lots of guns to loot and heavily armed enemies to shoot, try to shoot everyone on the map and survive in order to win each round.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/rgvqry48zgqwwg9drji08bpwnvamr57r/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, Battlegrounds, CSGO, Gun, Killing, Shoot, Shoot 'Em Up, Shooter, Shooting, Unity3D, War, WebGL",
        "thumb": "https://img.gamemonetize.com/rgvqry48zgqwwg9drji08bpwnvamr57r/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "19754",
        "title": "Noob vs Hacker Zombie",
        "description": "In the Noob and the Hacker series, the hacker gets sick and turns into a zombie, and Noob goes after him to kill him. noob escape hacker has sword in hand and he will kill noob. Noob runs away to avoid dying. The noob needs to reach the portal ahead of time or he may die. Oh beware, poisonous water is rising, you can never look back. You have to run all the time to not die.",
        "instructions": " WD to move Arrow Keys to move Mobile Touch Control Double jump is active in the game ",
        "url": "https://html5.gamemonetize.com/a6jygvm79nly34vmiqdydr4gyk8w592h/",
        "category": "Arcade",
        "tags": "1 Player, 2D, Action, Adventure, Android, Arcade, Minecraft, Mobile",
        "thumb": "https://img.gamemonetize.com/a6jygvm79nly34vmiqdydr4gyk8w592h/512x384.jpg",
        "width": "800",
        "height": "600"
    },
    {
        "id": "19721",
        "title": "City Takeover 3d Game",
        "description": "City Takeover is an arcade game that is both entertaining and addictive. It's a three-dimensional game. In this game, you can take over as many cities as you like. It's time to find out if you're a capable army commander! You can take the city when the number of your soldiers equals or exceeds the number of people in the city to be captured. You must also keep an eye out for the enemy creeping into your city! The team with the most brains wins! Will you be victorious in the end? Come give it a shot! Best of luck!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/qf5vxhqfu08rk9aqjksr8uwshi14m50n/",
        "category": "3D",
        "tags": "Arcade, Avoid, Boy, city, Kids, Obstacle, Skill, Strategy, War",
        "thumb": "https://img.gamemonetize.com/qf5vxhqfu08rk9aqjksr8uwshi14m50n/512x384.jpg",
        "width": "1080",
        "height": "1920"
    },
    {
        "id": "19682",
        "title": "Makeup-Artist-Fashion-Salon-Game",
        "description": "Why not become a makeup artist? Make up with your style and pick your favorite match. There are many types of cosmetics that can be used here. It's very interesting. You can use foundation, eye makeup, lipstick, hairstyle, necklace and earrings to dress up. Tons of different designs for you to discover, cloud, butterfly, rainbow, Christmas and Halloween, everything in trend can be an inspiration for your style.Come and challenge your fashion skill now!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/p515epm3zg2usxwdjdxc0o9lcgjhg3wq/",
        "category": "Girls",
        "tags": "Boy, Cute, Fashion, Girls, Hypercasual, Kid",
        "thumb": "https://img.gamemonetize.com/p515epm3zg2usxwdjdxc0o9lcgjhg3wq/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "19657",
        "title": "Buildy Island 3d Game",
        "description": "This is a trending idle game, a new Sims experience is about to begin. You go from being a woodcutter with nothing to an island owner with a wealth of specialties what an experience. At first, you need to practice logging, chopping wood and collecting crops, then you can choose what kind of house to build and who to hire for the job, this time you don't need to do it yourself, professional managers will be your right-hand man and easily manage your personal world online. You're going to love farm life!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/fetigp7yeci9yf3fxakwsa7c2x8de2q0/",
        "category": "3D",
        "tags": "3D, Boys, Fighting, Hypercasual, Kids, War",
        "thumb": "https://img.gamemonetize.com/fetigp7yeci9yf3fxakwsa7c2x8de2q0/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19640",
        "title": "Poppy Strike",
        "description": "Poppy Strike is a 3D shooting game which features gun game mode with big arsenal of weapons and famous dust 2 map crowded with huggy wuggy, your mission is to shoot all incoming huggy wuggy and try to survive by the end of each round in order to get new weapons.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump P - Pause ",
        "url": "https://html5.gamemonetize.com/4wxvll34uscoiq4xxsh4ubrstuzwm5xe/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, CSGO, Gun, Shoot, Shoot 'Em Up, Shooter, Shooting, Unity3D, WebGL",
        "thumb": "https://img.gamemonetize.com/4wxvll34uscoiq4xxsh4ubrstuzwm5xe/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "19603",
        "title": "Pou Caring Game",
        "description": "POU Caring is an interesting and cute POU caring game. How would you take care of your own alien pet? Feed him, bathe him, play with him and watch him grow up. With the upgrading of the level, unlock different wallpaper, clothing to meet your unique taste. How would you DIY your own POU?",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/px2h9zdzq6txs4i2hkg6ck5pqiu8icxw/",
        "category": "Girls",
        "tags": "Boys, Cute, Dress Up, Kids",
        "thumb": "https://img.gamemonetize.com/px2h9zdzq6txs4i2hkg6ck5pqiu8icxw/512x384.jpg",
        "width": "504",
        "height": "800"
    },
    {
        "id": "19563",
        "title": "Mad City Matrix",
        "description": "Mad City Matrix features intense combat with agents in big open world city, use powerful punches and lots of weapons to defeat all incoming agents and try to survive each level before the time runs out.",
        "instructions": "WASD - Move LMB - Shoot RMB - Aim Mouse Wheel - Change weapon R - Reload Space - Jump T - Bullet time ",
        "url": "https://html5.gamemonetize.com/hvw3bkpx0nx4m5v3cigplk9uosae5ila/",
        "category": "Shooting",
        "tags": "1 Player, 3D, 3D Games, Action, Fighting, Shoot, Shoot 'Em Up, Shooter, Shooting, Unity3D, WebGL",
        "thumb": "https://img.gamemonetize.com/hvw3bkpx0nx4m5v3cigplk9uosae5ila/512x384.jpg",
        "width": "960",
        "height": "600"
    },
    {
        "id": "19519",
        "title": "Overloaded Bus 3d Game",
        "description": "Have you ever felt the crowded bus in the morning rush hour? Come and join the Overloaded Bus! The most fun squeeze the bus game of the year is here, Overloaded Bus is a super fun puzzle game and a free-to-play online game for kids. All you have to do is press and hold the screen to get the passengers on and off the bus, be careful not to overload the bus or it will burst. Get on the bus!have fun!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/qjmw9t1p0mdrj92gg2znc5b6t9vt3bfm/",
        "category": "3D",
        "tags": "bus, Hypercasual, Puzzle, running",
        "thumb": "https://img.gamemonetize.com/qjmw9t1p0mdrj92gg2znc5b6t9vt3bfm/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19508",
        "title": "Breakanoid",
        "description": "Breakanoid is a brick breaker game, in the Arkanoid online style. The Vaus Mothership has already eradicated many solar systems. Commander, your mission is to attack and destroy the Vaus Mothership through 100 levels of intense action with balls and bricks. You will encounter walls, enemies and bosses that will block your way in this breakout game online. Stop the Vaus Mothership to save the galaxy. Break the bricks with Breakanoid ! Features: - 100 unique levels / 10 zones. - 10 enemies types / 5 bosses. - 8 power ups. - Modern and futuristic graphics. - Immersive sound and musical atmosphere (Action / Synthwave). - Highscores Leaderboard.",
        "instructions": "- Keyboard - Left and right keys for move Space key for ball release - Mouse - Left mouse button for ball release - Tactile - Touch up for ball release ",
        "url": "https://html5.gamemonetize.com/gbbx1f761zj1xvj8xhdr2hefzadzu0nf/",
        "category": "Arcade",
        "tags": ".io, .io Games, Action, Adult, Alien, Arcade, Arkanoid, Ball, Batman, Battle, Block, Bricks, Casino, Clans, Clash, Classic, CSGO, Dragon Ball Z, Game, Google, gta, Gun, Highscore, HTML5, IO, Lego, Love, Mario, Mine, Minecraft, Mobile, Obstacle, PacMan, Panda, Pinball, Planet, Pokemon, Retro, Robot, Seduction, Shoot, Shoot 'Em Up, Shooter, Shooting, Simpson, Space, Spaceship, Spiderman, Spongebob, Tetris, War, weapons, WebGL, Worms, Zombie",
        "thumb": "https://img.gamemonetize.com/gbbx1f761zj1xvj8xhdr2hefzadzu0nf/512x384.jpg",
        "width": "600",
        "height": "800"
    },
    {
        "id": "19487",
        "title": "Ball Paint 3D Game",
        "description": "Ball Paint 3D is a relaxing, simple, and fun game for kids, free online. You only have to find the balls of the same color within the limited number of balls given to you to pass the game, with beautiful 3D graphics to give you the best gaming experience. It's a battle of the brains, do you dare to challenge? Come and join us and keep breaking through yourself! Good luck and have fun!",
        "instructions": "Mouse or tap to play ",
        "url": "https://html5.gamemonetize.com/cellphkb1r8zdnxtwrk18zg5nzobo1im/",
        "category": "3D",
        "tags": "Ball, Boys, Color, Girls, Hypercasual, Kids",
        "thumb": "https://img.gamemonetize.com/cellphkb1r8zdnxtwrk18zg5nzobo1im/512x384.jpg",
        "width": "750",
        "height": "1334"
    },
    {
        "id": "19484",
        "title": "Sushi Rush",
        "description": "Cute little sushi rush through the restaurant. There are deadly plates all over the place. One step on any of those and sushi is going to be eaten right away. Also jumping into the water will end badly for our character.",
        "instructions": "Swipe left right or up to move Don t fall into the water and avoid the plates ",
        "url": "https://html5.gamemonetize.com/ol4fa3wcwfg8jgqszieblezfjo4ls4fh/",
        "category": "Hypercasual",
        "tags": "Action, Arcade, Funny, jump",
        "thumb": "https://img.gamemonetize.com/ol4fa3wcwfg8jgqszieblezfjo4ls4fh/512x384.jpg",
        "width": "800",
        "height": "600"
    }
]